const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description:
      "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A cozy beachfront cottage with ocean views.",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    type: "Cottage",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 900,
    amenities: ["Wi-Fi", "Kitchen", "Free parking", "Ocean view", "Patio"],
    availability: ["2025-09-01", "2025-09-02", "2025-09-03", "2025-09-04", "2025-09-05"],
    bookedDates: ["2025-08-20", "2025-08-21", "2025-08-22"],
    minimumStay: 2,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Beautiful place! The ocean view was amazing.",
        rating: 5,
        date: "2025-08-25",
      },
    ],
    host: {
      name: "Jane Doe",
      contact: "555-123-4567",
      email: "jane.doe@example.com",
      verified: true,
    },
    status: "active",
    tags: ["beach", "vacation", "cozy", "cottage", "oceanfront"],
    slug: "cozy-beachfront-cottage-malibu",
    cancellationPolicy: "Full refund 7 days prior to check-in.",
  },
  {
    title: "Modern Loft in Downtown",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A stylish loft in a city downtown.",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    type: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    area: 750,
    amenities: ["Wi-Fi", "Kitchen", "Gym access", "City view", "Elevator"],
    availability: ["2025-09-10", "2025-09-11", "2025-09-12"],
    bookedDates: ["2025-08-28", "2025-08-29"],
    minimumStay: 3,
    checkIn: "4:00 PM",
    checkOut: "10:00 AM",
    rating: 4.5,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Great location, close to everything!",
        rating: 4,
        date: "2025-08-30",
      },
    ],
    host: {
      name: "John Smith",
      contact: "555-987-6543",
      email: "john.smith@example.com",
      verified: true,
    },
    status: "active",
    tags: ["city", "urban", "modern", "loft", "new york"],
    slug: "modern-loft-downtown-nyc",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Mountain Retreat",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A peaceful cabin in the mountains.",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    type: "Cabin",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    area: 1500,
    amenities: ["Fireplace", "Hot tub", "Wi-Fi", "Mountain view", "Hiking trails"],
    availability: ["2025-10-05", "2025-10-06", "2025-10-07"],
    bookedDates: ["2025-09-01", "2025-09-02"],
    minimumStay: 4,
    checkIn: "4:00 PM",
    checkOut: "10:00 AM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Absolutely stunning location, so peaceful and beautiful.",
        rating: 5,
        date: "2025-09-03",
      },
    ],
    host: {
      name: "Michael Lee",
      contact: "555-555-5555",
      email: "michael.lee@example.com",
      verified: true,
    },
    status: "active",
    tags: ["mountain", "retreat", "cabin", "nature", "aspen"],
    slug: "mountain-retreat-aspen",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Historic Villa in Tuscany",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A historic villa in the Tuscan countryside.",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    type: "Villa",
    bedrooms: 5,
    bathrooms: 4,
    guests: 10,
    area: 3000,
    amenities: ["Private pool", "Garden", "Wi-Fi", "Vineyard views", "Wine cellar"],
    availability: ["2025-11-01", "2025-11-02", "2025-11-03", "2025-11-04"],
    bookedDates: ["2025-10-15", "2025-10-16"],
    minimumStay: 7,
    checkIn: "2:00 PM",
    checkOut: "10:00 AM",
    rating: 5.0,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "A truly magical stay. The villa is perfect.",
        rating: 5,
        date: "2025-10-18",
      },
    ],
    host: {
      name: "Sofia Rossi",
      contact: "555-333-2222",
      email: "sofia.rossi@example.com",
      verified: true,
    },
    status: "active",
    tags: ["villa", "tuscany", "historic", "italy", "vineyard"],
    slug: "historic-villa-tuscany-florence",
    cancellationPolicy: "Full refund 30 days prior to check-in.",
  },
  {
    title: "Secluded Treehouse Getaway",
    description:
      "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A secluded treehouse nestled in a forest.",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    type: "Treehouse",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    area: 500,
    amenities: ["Wi-Fi", "Balcony", "Forest view", "Kitchenette", "Hot tub"],
    availability: ["2025-09-15", "2025-09-16", "2025-09-17"],
    bookedDates: ["2025-09-05"],
    minimumStay: 1,
    checkIn: "3:00 PM",
    checkOut: "12:00 PM",
    rating: 4.7,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Such a unique and peaceful experience. Loved it!",
        rating: 5,
        date: "2025-09-08",
      },
    ],
    host: {
      name: "Emily White",
      contact: "555-444-3333",
      email: "emily.white@example.com",
      verified: true,
    },
    status: "active",
    tags: ["treehouse", "nature", "secluded", "portland", "unique"],
    slug: "secluded-treehouse-getaway-portland",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Beachfront Paradise",
    description:
      "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A luxurious beachfront condo.",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    type: "Condo",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    area: 1800,
    amenities: ["Beach access", "Private pool", "Wi-Fi", "Kitchen", "Balcony"],
    availability: ["2025-10-20", "2025-10-21", "2025-10-22", "2025-10-23"],
    bookedDates: ["2025-09-10", "2025-09-11"],
    minimumStay: 5,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The perfect beach vacation. Everything was fantastic.",
        rating: 5,
        date: "2025-09-15",
      },
    ],
    host: {
      name: "Carlos Rodriguez",
      contact: "555-888-9999",
      email: "carlos.r@example.com",
      verified: true,
    },
    status: "active",
    tags: ["beach", "vacation", "cancun", "mexico", "condo"],
    slug: "beachfront-paradise-cancun",
    cancellationPolicy: "Full refund 14 days prior to check-in.",
  },
  {
    title: "Rustic Cabin by the Lake",
    description:
      "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A rustic cabin by a serene lake.",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    type: "Cabin",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 1000,
    amenities: ["Wi-Fi", "Kitchen", "Lake access", "Fishing gear", "Kayaks"],
    availability: ["2025-10-01", "2025-10-02", "2025-10-03"],
    bookedDates: ["2025-09-20", "2025-09-21"],
    minimumStay: 2,
    checkIn: "4:00 PM",
    checkOut: "11:00 AM",
    rating: 4.6,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The cabin was charming and the lake was beautiful.",
        rating: 4,
        date: "2025-09-22",
      },
    ],
    host: {
      name: "Robert Green",
      contact: "555-111-2222",
      email: "robert.g@example.com",
      verified: false,
    },
    status: "active",
    tags: ["cabin", "lake", "outdoors", "fishing", "tahoe"],
    slug: "rustic-cabin-lake-tahoe",
    cancellationPolicy: "Flexible cancellation policy.",
  },
  {
    title: "Luxury Penthouse with City Views",
    description:
      "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A luxurious penthouse with city skyline views.",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 4,
    guests: 8,
    area: 4000,
    amenities: ["Private balcony", "Gym", "Pool", "Wi-Fi", "Parking"],
    availability: ["2025-11-15", "2025-11-16", "2025-11-17"],
    bookedDates: ["2025-10-05"],
    minimumStay: 3,
    checkIn: "4:00 PM",
    checkOut: "11:00 AM",
    rating: 5.0,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The views were incredible! A truly luxurious stay.",
        rating: 5,
        date: "2025-10-07",
      },
    ],
    host: {
      name: "Sarah Johnson",
      contact: "555-777-8888",
      email: "sarah.j@example.com",
      verified: true,
    },
    status: "active",
    tags: ["luxury", "penthouse", "city", "la", "views"],
    slug: "luxury-penthouse-los-angeles",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description:
      "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A ski chalet in the snowy Swiss Alps.",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    type: "Chalet",
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    area: 2500,
    amenities: ["Ski-in/ski-out", "Fireplace", "Hot tub", "Mountain views", "Ski storage"],
    availability: ["2025-12-01", "2025-12-02", "2025-12-03", "2025-12-04"],
    bookedDates: ["2025-11-20"],
    minimumStay: 7,
    checkIn: "4:00 PM",
    checkOut: "10:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The perfect ski trip! Chalet was beautiful.",
        rating: 5,
        date: "2025-11-22",
      },
    ],
    host: {
      name: "Hans Muller",
      contact: "555-666-7777",
      email: "hans.muller@example.com",
      verified: true,
    },
    status: "active",
    tags: ["ski", "chalet", "alps", "switzerland", "winter"],
    slug: "ski-in-out-chalet-verbier",
    cancellationPolicy: "Full refund 30 days prior to check-in.",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description:
      "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A safari lodge in the Serengeti.",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    type: "Lodge",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    area: 1200,
    amenities: ["Safari guide", "Game drives", "Wi-Fi", "Pool", "Restaurant"],
    availability: ["2026-01-10", "2026-01-11", "2026-01-12"],
    bookedDates: ["2025-12-01"],
    minimumStay: 3,
    checkIn: "2:00 PM",
    checkOut: "10:00 AM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "An unforgettable experience! The wildlife was incredible.",
        rating: 5,
        date: "2025-12-03",
      },
    ],
    host: {
      name: "Aisha Mohammed",
      contact: "555-000-1111",
      email: "aisha.m@example.com",
      verified: true,
    },
    status: "active",
    tags: ["safari", "wildlife", "lodge", "serengeti", "tanzania"],
    slug: "safari-lodge-serengeti",
    cancellationPolicy: "Full refund 30 days prior to check-in.",
  },
  {
    title: "Historic Canal House",
    description:
      "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A historic canal house in Amsterdam.",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    type: "House",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 1200,
    amenities: ["Wi-Fi", "Kitchen", "City view", "Bike rentals", "Historic features"],
    availability: ["2025-10-01", "2025-10-02", "2025-10-03"],
    bookedDates: ["2025-09-10", "2025-09-11"],
    minimumStay: 3,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.7,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Charming house and a great location to explore the city.",
        rating: 5,
        date: "2025-09-15",
      },
    ],
    host: {
      name: "Dirk van der Meer",
      contact: "555-444-5555",
      email: "dirk.v@example.com",
      verified: true,
    },
    status: "active",
    tags: ["historic", "amsterdam", "canal", "city", "house"],
    slug: "historic-canal-house-amsterdam",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Private Island Retreat",
    description:
      "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A luxurious private island retreat in Fiji.",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    type: "Island",
    bedrooms: 6,
    bathrooms: 6,
    guests: 12,
    area: 5000,
    amenities: ["Private chef", "Boat", "Snorkeling gear", "Private beach", "Wi-Fi"],
    availability: ["2026-02-01", "2026-02-02", "2026-02-03"],
    bookedDates: ["2026-01-20"],
    minimumStay: 7,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    rating: 5.0,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "A once-in-a-lifetime experience. The ultimate luxury.",
        rating: 5,
        date: "2026-01-22",
      },
    ],
    host: {
      name: "David Chen",
      contact: "555-999-0000",
      email: "david.c@example.com",
      verified: true,
    },
    status: "active",
    tags: ["luxury", "private island", "fiji", "vacation", "exclusive"],
    slug: "private-island-retreat-fiji",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description:
      "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2gl2FjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A charming cottage in the Cotswolds.",
    },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    type: "Cottage",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 800,
    amenities: ["Fireplace", "Garden", "Wi-Fi", "Kitchen", "Hiking trails"],
    availability: ["2025-10-15", "2025-10-16", "2025-10-17"],
    bookedDates: ["2025-09-25", "2025-09-26"],
    minimumStay: 2,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Beautiful cottage, felt like a fairytale!",
        rating: 5,
        date: "2025-09-28",
      },
    ],
    host: {
      name: "Oliver Smith",
      contact: "555-123-1234",
      email: "oliver.s@example.com",
      verified: true,
    },
    status: "active",
    tags: ["cottage", "cotswolds", "charming", "uk", "countryside"],
    slug: "charming-cottage-cotswolds",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Historic Brownstone in Boston",
    description:
      "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A historic brownstone in Boston.",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    type: "Townhouse",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    area: 1800,
    amenities: ["Fireplace", "Wi-Fi", "Kitchen", "City view", "Parking"],
    availability: ["2025-11-20", "2025-11-21", "2025-11-22"],
    bookedDates: ["2025-11-10"],
    minimumStay: 3,
    checkIn: "4:00 PM",
    checkOut: "11:00 AM",
    rating: 4.7,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Beautiful and well-maintained historic home.",
        rating: 5,
        date: "2025-11-12",
      },
    ],
    host: {
      name: "Robert Adams",
      contact: "555-555-1111",
      email: "robert.a@example.com",
      verified: true,
    },
    status: "active",
    tags: ["historic", "brownstone", "boston", "city", "house"],
    slug: "historic-brownstone-boston",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description:
      "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A beachfront bungalow with a private pool in Bali.",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    type: "Bungalow",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    area: 1100,
    amenities: ["Private pool", "Beach access", "Wi-Fi", "Kitchen", "Garden"],
    availability: ["2025-12-05", "2025-12-06", "2025-12-07"],
    bookedDates: ["2025-11-25"],
    minimumStay: 5,
    checkIn: "2:00 PM",
    checkOut: "12:00 PM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "A slice of paradise! The pool was fantastic.",
        rating: 5,
        date: "2025-11-27",
      },
    ],
    host: {
      name: "Putu Indra",
      contact: "555-333-1111",
      email: "putu.i@example.com",
      verified: true,
    },
    status: "active",
    tags: ["bungalow", "bali", "beach", "indonesia", "pool"],
    slug: "beachfront-bungalow-bali",
    cancellationPolicy: "Full refund 14 days prior to check-in.",
  },
  {
    title: "Mountain View Cabin in Banff",
    description:
      "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A cozy cabin with mountain views in Banff.",
    },
    price: 1500,
    location: "Banff",
    country: "Canada",
    type: "Cabin",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    area: 1400,
    amenities: ["Fireplace", "Hot tub", "Mountain views", "Wi-Fi", "Hiking trails"],
    availability: ["2026-01-15", "2026-01-16", "2026-01-17"],
    bookedDates: ["2025-12-25", "2025-12-26"],
    minimumStay: 4,
    checkIn: "4:00 PM",
    checkOut: "10:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Incredible views and a very comfortable cabin.",
        rating: 5,
        date: "2025-12-28",
      },
    ],
    host: {
      name: "Ethan Clark",
      contact: "555-222-3333",
      email: "ethan.c@example.com",
      verified: true,
    },
    status: "active",
    tags: ["cabin", "mountains", "banff", "canada", "rockies"],
    slug: "mountain-view-cabin-banff",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Art Deco Apartment in Miami",
    description:
      "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "An art deco apartment in Miami's South Beach.",
    },
    price: 1600,
    location: "Miami",
    country: "United States",
    type: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    area: 900,
    amenities: ["Wi-Fi", "Pool", "Beach access", "City view", "Parking"],
    availability: ["2025-11-05", "2025-11-06", "2025-11-07"],
    bookedDates: ["2025-10-25"],
    minimumStay: 2,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.6,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Stylish and well-located apartment. Great stay!",
        rating: 5,
        date: "2025-10-27",
      },
    ],
    host: {
      name: "Sophia Martinez",
      contact: "555-666-3333",
      email: "sophia.m@example.com",
      verified: true,
    },
    status: "active",
    tags: ["art deco", "miami", "apartment", "south beach", "city"],
    slug: "art-deco-apartment-miami",
    cancellationPolicy: "Flexible cancellation policy.",
  },
  {
    title: "Tropical Villa in Phuket",
    description:
      "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A tropical villa with an infinity pool in Phuket.",
    },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    type: "Villa",
    bedrooms: 4,
    bathrooms: 4,
    guests: 8,
    area: 2500,
    amenities: ["Private pool", "Garden", "Beach access", "Wi-Fi", "Daily maid service"],
    availability: ["2025-12-20", "2025-12-21", "2025-12-22"],
    bookedDates: ["2025-12-01"],
    minimumStay: 5,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Paradise on earth! The villa and staff were amazing.",
        rating: 5,
        date: "2025-12-03",
      },
    ],
    host: {
      name: "Chai Somchai",
      contact: "555-444-2222",
      email: "chai.s@example.com",
      verified: true,
    },
    status: "active",
    tags: ["villa", "phuket", "tropical", "thailand", "luxury"],
    slug: "tropical-villa-phuket",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Historic Castle in Scotland",
    description:
      "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A historic castle in the Scottish Highlands.",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    type: "Castle",
    bedrooms: 8,
    bathrooms: 6,
    guests: 16,
    area: 8000,
    amenities: ["Fireplace", "Wi-Fi", "Garden", "History", "Private tours"],
    availability: ["2026-03-10", "2026-03-11", "2026-03-12"],
    bookedDates: ["2026-02-15"],
    minimumStay: 7,
    checkIn: "2:00 PM",
    checkOut: "10:00 AM",
    rating: 5.0,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Felt like a king! The castle is magnificent.",
        rating: 5,
        date: "2026-02-17",
      },
    ],
    host: {
      name: "Lachlan Stewart",
      contact: "555-888-7777",
      email: "lachlan.s@example.com",
      verified: true,
    },
    status: "active",
    tags: ["castle", "scotland", "historic", "royalty", "highlands"],
    slug: "historic-castle-scotland",
    cancellationPolicy: "Full refund 30 days prior to check-in.",
  },
  {
    title: "Desert Oasis in Dubai",
    description:
      "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A luxury desert oasis with a private pool in Dubai.",
    },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    type: "Villa",
    bedrooms: 3,
    bathrooms: 3,
    guests: 6,
    area: 2000,
    amenities: ["Private pool", "Desert safari", "Wi-Fi", "Chef on call", "Camel rides"],
    availability: ["2026-01-25", "2026-01-26", "2026-01-27"],
    bookedDates: ["2026-01-10"],
    minimumStay: 3,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "An incredible and unique luxury experience.",
        rating: 5,
        date: "2026-01-12",
      },
    ],
    host: {
      name: "Ahmed Al-Maktoum",
      contact: "555-111-3333",
      email: "ahmed.a@example.com",
      verified: true,
    },
    status: "active",
    tags: ["desert", "dubai", "luxury", "oasis", "villa"],
    slug: "desert-oasis-dubai",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description:
      "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A rustic log cabin in Montana.",
    },
    price: 1100,
    location: "Montana",
    country: "United States",
    type: "Cabin",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 1000,
    amenities: ["Fireplace", "Wi-Fi", "Kitchen", "Hiking trails", "Outdoor grill"],
    availability: ["2025-10-05", "2025-10-06", "2025-10-07"],
    bookedDates: ["2025-09-20", "2025-09-21"],
    minimumStay: 3,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.7,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Perfect for a quiet escape into nature.",
        rating: 5,
        date: "2025-09-23",
      },
    ],
    host: {
      name: "Jessica Brown",
      contact: "555-222-1111",
      email: "jessica.b@example.com",
      verified: true,
    },
    status: "active",
    tags: ["cabin", "montana", "rustic", "nature", "cozy"],
    slug: "rustic-log-cabin-montana",
    cancellationPolicy: "Flexible cancellation policy.",
  },
  {
    title: "Beachfront Villa in Greece",
    description:
      "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A beachfront villa in Greece.",
    },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    type: "Villa",
    bedrooms: 3,
    bathrooms: 3,
    guests: 6,
    area: 1800,
    amenities: ["Private pool", "Beach access", "Wi-Fi", "Kitchen", "Terrace"],
    availability: ["2026-06-10", "2026-06-11", "2026-06-12"],
    bookedDates: ["2026-05-20"],
    minimumStay: 7,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The views and location are unbeatable. A perfect vacation.",
        rating: 5,
        date: "2026-05-22",
      },
    ],
    host: {
      name: "Eleni Papadopoulos",
      contact: "555-777-2222",
      email: "eleni.p@example.com",
      verified: true,
    },
    status: "active",
    tags: ["villa", "greece", "mykonos", "beach", "mediterranean"],
    slug: "beachfront-villa-mykonos",
    cancellationPolicy: "Full refund 14 days prior to check-in.",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description:
      "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "An eco-friendly treehouse in a forest.",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    type: "Treehouse",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    area: 600,
    amenities: ["Solar power", "Rainwater harvesting", "Wi-Fi", "Forest view", "Hiking trails"],
    availability: ["2025-11-20", "2025-11-21", "2025-11-22"],
    bookedDates: ["2025-11-10"],
    minimumStay: 2,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    rating: 4.7,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Loved the sustainable approach and the beautiful surroundings.",
        rating: 5,
        date: "2025-11-12",
      },
    ],
    host: {
      name: "Diego Garcia",
      contact: "555-333-5555",
      email: "diego.g@example.com",
      verified: true,
    },
    status: "active",
    tags: ["eco-friendly", "treehouse", "costa rica", "nature", "sustainable"],
    slug: "eco-friendly-treehouse-costa-rica",
    cancellationPolicy: "Flexible cancellation policy.",
  },
  {
    title: "Historic Cottage in Charleston",
    description:
      "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A historic cottage with a private garden in Charleston.",
    },
    price: 1600,
    location: "Charleston",
    country: "United States",
    type: "Cottage",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    area: 1200,
    amenities: ["Garden", "Wi-Fi", "Kitchen", "Historic features", "Walking distance to attractions"],
    availability: ["2025-11-10", "2025-11-11", "2025-11-12"],
    bookedDates: ["2025-10-30"],
    minimumStay: 3,
    checkIn: "4:00 PM",
    checkOut: "11:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Charming cottage, perfect for exploring Charleston.",
        rating: 5,
        date: "2025-11-01",
      },
    ],
    host: {
      name: "Susan Miller",
      contact: "555-999-8888",
      email: "susan.m@example.com",
      verified: true,
    },
    status: "active",
    tags: ["historic", "charleston", "cottage", "charming", "garden"],
    slug: "historic-cottage-charleston",
    cancellationPolicy: "Moderate cancellation policy.",
  },
  {
    title: "Modern Apartment in Tokyo",
    description:
      "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      altText: "A modern apartment with city views in Tokyo.",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 1000,
    amenities: ["Wi-Fi", "Kitchen", "City view", "Subway access", "Elevator"],
    availability: ["2025-12-01", "2025-12-02", "2025-12-03"],
    bookedDates: ["2025-11-15"],
    minimumStay: 2,
    checkIn: "3:00 PM",
    checkOut: "10:00 AM",
    rating: 4.6,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "Convenient and modern, perfect for exploring Tokyo.",
        rating: 5,
        date: "2025-11-17",
      },
    ],
    host: {
      name: "Kenji Tanaka",
      contact: "555-111-9999",
      email: "kenji.t@example.com",
      verified: true,
    },
    status: "active",
    tags: ["modern", "tokyo", "apartment", "city", "japan"],
    slug: "modern-apartment-tokyo",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description:
      "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A lakefront cabin in New Hampshire.",
    },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    type: "Cabin",
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    area: 1100,
    amenities: ["Lake access", "Fishing", "Kayaks", "Fire pit", "Wi-Fi"],
    availability: ["2025-10-25", "2025-10-26", "2025-10-27"],
    bookedDates: ["2025-10-15"],
    minimumStay: 2,
    checkIn: "3:00 PM",
    checkOut: "11:00 AM",
    rating: 4.8,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "A peaceful and relaxing lakeside retreat.",
        rating: 5,
        date: "2025-10-17",
      },
    ],
    host: {
      name: "David Wilson",
      contact: "555-555-7777",
      email: "david.w@example.com",
      verified: true,
    },
    status: "active",
    tags: ["cabin", "lakefront", "new hampshire", "nature", "outdoors"],
    slug: "lakefront-cabin-new-hampshire",
    cancellationPolicy: "Flexible cancellation policy.",
  },
  {
    title: "Luxury Villa in the Maldives",
    description:
      "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A luxury overwater villa in the Maldives.",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    type: "Villa",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    area: 1500,
    amenities: ["Private pool", "Overwater deck", "Wi-Fi", "Snorkeling", "All-inclusive options"],
    availability: ["2026-03-05", "2026-03-06", "2026-03-07"],
    bookedDates: ["2026-02-20"],
    minimumStay: 5,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    rating: 5.0,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "A dream come true! The perfect romantic getaway.",
        rating: 5,
        date: "2026-02-22",
      },
    ],
    host: {
      name: "Maria Silva",
      contact: "555-888-6666",
      email: "maria.s@example.com",
      verified: true,
    },
    status: "active",
    tags: ["luxury", "maldives", "villa", "overwater", "romantic"],
    slug: "luxury-villa-maldives",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Ski Chalet in Aspen",
    description:
      "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A luxurious ski chalet in Aspen.",
    },
    price: 4000,
    location: "Aspen",
    country: "United States",
    type: "Chalet",
    bedrooms: 5,
    bathrooms: 4,
    guests: 10,
    area: 3000,
    amenities: ["Ski-in/ski-out", "Hot tub", "Fireplace", "Wi-Fi", "Game room"],
    availability: ["2026-01-10", "2026-01-11", "2026-01-12"],
    bookedDates: ["2025-12-28"],
    minimumStay: 7,
    checkIn: "4:00 PM",
    checkOut: "10:00 AM",
    rating: 4.9,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The perfect place for a family ski trip. So spacious and luxurious.",
        rating: 5,
        date: "2025-12-30",
      },
    ],
    host: {
      name: "Alex Parker",
      contact: "555-333-2222",
      email: "alex.p@example.com",
      verified: true,
    },
    status: "active",
    tags: ["ski", "aspen", "chalet", "luxury", "winter"],
    slug: "ski-chalet-aspen",
    cancellationPolicy: "Strict cancellation policy.",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description:
      "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      altText: "A secluded beach house in Costa Rica.",
    },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    area: 1500,
    amenities: ["Beach access", "Wi-Fi", "Kitchen", "Outdoor shower", "Surfboards"],
    availability: ["2026-02-15", "2026-02-16", "2026-02-17"],
    bookedDates: ["2026-02-01"],
    minimumStay: 4,
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    rating: 4.7,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        comment: "The perfect place to relax and enjoy the beach.",
        rating: 5,
        date: "2026-02-03",
      },
    ],
    host: {
      name: "Luis Rodriguez",
      contact: "555-444-1111",
      email: "luis.r@example.com",
      verified: true,
    },
    status: "active",
    tags: ["beach", "house", "costa rica", "secluded", "surfing"],
    slug: "secluded-beach-house-costa-rica",
    cancellationPolicy: "Moderate cancellation policy.",
  },
];

module.exports = { data: sampleListings };